/*

 PREY_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char PreyTiles[] = {0x07, 0x07, 0x07, 0x05, 0xFF, 0xFF, 0xFF, 0xFF,
                             0xFC, 0xFC, 0xFC, 0xFC, 0xCC, 0xCC, 0xCC, 0xCC,
                             0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x24, 0x3C,
                             0x24, 0x3C, 0x18, 0x18, 0x00, 0x00, 0x00, 0x00};

/* End of PREY_TILES.C */
