/*

 SNAKE_BODY.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define SnakeBodyBank 0
/* Start of tile array. */
extern unsigned char SnakeBody[];

// TODO: Consider using defines instead.
extern const unsigned char kSnakeBody_EMPTY;
extern const unsigned char kSnakeBody_RIGHT;
extern const unsigned char kSnakeBody_LEFT;
extern const unsigned char kSnakeBody_UP;
extern const unsigned char kSnakeBody_DOWN;
extern const unsigned char kSnakeBody_LEFT_DOWN;
extern const unsigned char kSnakeBody_LEFT_UP;
extern const unsigned char kSnakeBody_RIGHT_DOWN;
extern const unsigned char kSnakeBody_RIGHT_UP;
extern const unsigned char kSnakeBody_UP_RIGHT;
extern const unsigned char kSnakeBody_UP_LEFT;
extern const unsigned char kSnakeBody_DOWN_RIGHT;
extern const unsigned char kSnakeBody_DOWN_LEFT;
/* End of SNAKE_BODY.H */
