/*

 SNAKE_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Snake[] = {0x78, 0x78, 0xFF, 0xCF, 0xFF, 0xCF, 0xFF, 0xFF,
                         0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00,
                         0x79, 0x79, 0xFE, 0xCE, 0xFC, 0xCC, 0xFC, 0xFC,
                         0xFC, 0xFC, 0xFC, 0xFC, 0xFE, 0xFE, 0x01, 0x01};

/* End of SNAKE_SPRITE.C */
